# Generated by Django 4.1 on 2023-10-23 09:19

from django.conf import settings
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    """
    Transfert data from foreignkey director to directors
    """
    db_alias = schema_editor.connection.alias
    PhdStudent = apps.get_model("school", "PhdStudent")
    User = apps.get_model(settings.AUTH_USER_MODEL)

    for phdstudent in PhdStudent.objects.using(db_alias).all():
        if(phdstudent.director):
            phdstudent.directors.add(phdstudent.director)
        else:
            phdstudent.directors.add(User.objects.first())
        phdstudent.save()

def backwards_func(apps, schema_editor):
    """
    Transfert manytomany directors to director (foreignKey)
    """    
    db_alias = schema_editor.connection.alias
    PhdStudent = apps.get_model("school", "PhdStudent")

    for phdstudent in PhdStudent.objects.using(db_alias).all():
        if(phdstudent.directors):
            phdstudent.director = phdstudent.directors.first()
        else:
            phdstudent.director.id = 1
        phdstudent.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0012_add_visitingstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phdstudent',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.PROTECT, related_name='phd_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phdstudent',
            name='defense_date',
            field=models.DateField(help_text='Year is important', null=True),
        ),
        migrations.AddField(
            model_name='phdstudent',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='phd_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            forwards_func, 
            backwards_func
        ),
        migrations.RemoveField(
            model_name='phdstudent',
            name='director',
        ),
    ]
