# Generated by Django 5.1.15 on 2026-06-01 09:15

from django.db import migrations, models




def forwards_func(apps, schema_editor):
    Diffusion = apps.get_model('diffusion', 'Diffusion')
    for diffusion in Diffusion.objects.all():
        diffusion.published = True
        diffusion.save()

def backwards_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("diffusion", "0007_alter_artist_artwork_event_on_award_diffusion"),
    ]

    operations = [
        migrations.AddField(
            model_name="diffusion",
            name="online",
            field=models.BooleanField(
                default=False, help_text="ON / OFF : Online diffusion or not"
            ),
        ),
        migrations.AddField(
            model_name="diffusion",
            name="published",
            field=models.BooleanField(
                default=False,
                help_text="Diffusion information is validated and can be published",
            ),
        ),
        migrations.RunPython(forwards_func, backwards_func),
    ]

