# Generated by Django 4.1 on 2023-10-23 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0006_languagesfield_newversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['user__last_name', 'nickname']},
        ),
        migrations.AddField(
            model_name='artist',
            name='alphabetical_order',
            field=models.TextField(blank=True, help_text='Never displayed, discern first/last/nick name'),
        ),
        migrations.AddField(
            model_name='artist',
            name='collective',
            field=models.ManyToManyField(blank=True, help_text='collective artists, pairs, ...', to='people.artist'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
